name: Go Web App CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # STAGE 1: BUILD & UNIT TEST
      - name: Set up Go Environment
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # STAGE 2: STATIC CODE ANALYSIS (Configured to keep moving forward if it finds style bugs)
      - name: Run Code Analysis
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.54
        continue-on-error: true 

      # STAGE 3: DOCKER IMAGE BUILD & PUSH
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # (Make sure to replace 'ahmed49849' with your actual Docker Hub username below if different!)
      - name: Build and Push Production Container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ahmed49849/go-web-app:${{ github.sha }}
            ahmed49849/go-web-app:latest